### ISSUE TITLE
Vcs->branch() needs to be nullable

### ISSUE THREAD

**Issue by kaktusas2598** [jmleroux/circleci-php-client#51]
Hello @jmleroux ,

I think I found a few more issues here, mainly looking at Vcs model, and branch is not nullable, but it is possible for it be null, mainly when you trigger a new tagged release, in that case "vcs" contains "tag" key instead of a "branch" key, so is it possible to make branch() in Vcs nullable?

**Comment by jmleroux** [comment]
Fixed in v5.1.3
