### ISSUE TITLE
PHP 8.2 Version constraints

### ISSUE THREAD

**Issue by kaktusas2598** [jmleroux/circleci-php-client#54]
Hi @jmleroux , I have tested this package and it works fine on PHP 8.2, but it has version constraint for PHP 8.1, so I had to composer install with --ignore-platform-reqs flag, but I can't do this in production, so is it possible to improve version constraint so I can install package with PHP 8.2?

**Comment by jmleroux** [comment]
Of course it is possible, thanks for raising the issue! :pray:

**Comment by jmleroux** [comment]
Merged in master

**Comment by kaktusas2598** [comment]
Thanks! Are you planning to tag a new release with this fix soon?

**Comment by jmleroux** [comment]
v5.1.4 released

https://github.com/jmleroux/circleci-php-client/releases/tag/v5.1.4
